flowchart LR
   CAPI[Implement the Conversion API]
    Website --- B
    B -.- C
    B === D(<img src="https://i1.wp.com/observingfromspace.com/wp-content/uploads/2020/10/image-29.png"/>)


click B "http://www.github.com" "This is a tooltip for a link"
